#多环境切换  也可以从java -jar指定参数
spring:
  profiles:
    active: dev
    include: db
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  thymeleaf:
    cache: false
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
server:
  tomcat:
    uri-encoding: UTF-8
logging:
  config: classpath:logging-config.xml

logback:
  logdir: /home/q/www/music_service
  appname: music_service

threadPool:
  corePoolSize : 10
  maximumPoolSize : 50
  keepAliveTime : 600
  capacity : 700
